### PR TITLE
add discord_scraping_guild_id.py

### PR DESCRIPTION
**Pull request by Ikhari**
I've added a star too, please acc my pr. Thank you

### CODE REVIEW

**Comment by zal-ghiffari** [comment]
why retract the star? star it plis. if you can't follow the rule i will deleted your pr

**Comment by zal-ghiffari** [comment]
i add the invalid label, star again to change into accepted label

**Comment by Ikhari** [comment]
I actually don't need it anymore. because I need to wait for a few days for this pr accepted. but here the star. 🫠

**Comment by zal-ghiffari** [comment]
sorry sir the hacktoberfest not accepted without label

**Comment by Ikhari** [comment]
Nah just acc already my pr, don't worry about that.

**Comment by zal-ghiffari** [comment]
and i set your PR label invalid

**Comment by Ikhari** [comment]
bruh, I already give a star your repo, delete the invalid label and merge my pr !!!

**Pull request merged**
